name: Deploy to production environment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NOMAD_ADDR: ${{ secrets.PROD_NOMAD_ADDR }}
  IMAGE_TAG: ghcr.io/${{ github.repository }}:${{ github.sha }}
jobs:
  build:
    environment: production
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install dependencies
        run: npm ci

      - name: Generate grpc stubs
        run: npm run gen

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG -f Dockerfile .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to ghcr
        run: docker push $IMAGE_TAG

  deploy:
    environment: production
    runs-on: self-hosted
    needs: [build]
    steps:
      - uses: actions/checkout@v3

      - name: Get Nomad token from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.PROD_VAULT_ADDR }}
          method: userpass
          username: ${{ secrets.PROD_SERVICE_DEPLOYER_USERNAME }}
          password: ${{ secrets.PROD_SERVICE_DEPLOYER_PASSWORD }}
          secrets: nomad/creds/${{ secrets.PROD_SERVICE_DEPLOYER_USERNAME }} secret_id | NOMAD_TOKEN ;

      - name: Deploy job
        run: |
          sed -i -e "s|__IMAGE__|$IMAGE_TAG|g" service.nomad
          nomad job run -verbose service.nomad
